### ISSUE TITLE
Error on running srtrelay

### ISSUE THREAD

**Issue by manollas2015** [voc/srtrelay#13]
Hello,

srtrelay is giving error while trying to run.

./srtrelay: error while loading shared libraries: libsrt.so.1.4: cannot open shared object file: No such file or directory

**Comment by Garionion** [comment]
Did you install libsrt?

**Comment by v0tti** [comment]
After building libsrt I had to do `export LD_LIBRARY_PATH=/usr/local/lib64` for the relay to start working.
