### ISSUE TITLE
Bad stream quality with high RTT

### ISSUE THREAD

**Issue by taojishou** [voc/srtrelay#24]
rtt在150到200左右，推送花屏挺多，有啥参数可以控制吗，另外ffmpeg拉中继流转推flv经常出现
```
[flv @ 0x3753080] Error applying bitstream filters to an output packet for stream #1: Invalid data found when processing input
av_interleaved_write_frame(): Invalid data found when processing input
```

Translation:
The rtt is around 150 to 200, and there are quite a lot of blurry frames. Is there any parameter that can be controlled? In addition, ffmpeg pulls the relay stream and pushes the flv frequently.

**Comment by iSchluff** [comment]
Hi, have you tried tuning the latency in the server config? The default is only set to 200ms, but for an RTT of 200ms you will probably need to set the latency to atleast 500.

https://github.com/voc/srtrelay/blob/96cfd8728f42c18f9dbe13e920ce39d84b3c65ff/config.toml.example#L15-L19
