### ISSUE TITLE
Stream quality problems

### ISSUE THREAD

**Issue by ppumkin** [voc/srtrelay#29]
We using IRL LibeU Solo with the SRT transmit. I setup a docker image in OVH to relay to my production OBS.

But the stream quality is very bad. Lots of glitching and black out - as if its loosing the GOP? I blamed them for it but I setup a direct to studio SRT connection and the stream is perfect.

What could be causing this issue?

**Comment by iSchluff** [comment]
Hi, did you host the srtrelay at the same location as the studio?
The most likely case is different latency configuration for the SRT streams. If the configured latency is too low for the round trip time you may be losing packets.

**Comment by ppumkin** [comment]
No.. it wasn't same location.
We using SoloPro which uses LRT.. they push that to their server and then connects to a SRT from their cloud instance.
Now when I connect direct to my studio SRT direct.. works like a charm. 

srt-relay hosted in OVH on a VPS in docker. The reported latency between LiveU and SRT is apparety 1ms?? maybe same datacentre i got lucky
And then my studio connects to OVH and that reports a 60ms RTT as usuall.

Reading documents saying SRT will select the highest latency option. Did not matter what I configured anywhere. low, high - it was a mess always ;(

Thisis a massive shame because the CPU usage is nothing with hardly and RAM and I wanted to pull several feeds from srt relay. currently I am using antmedia which is elephant using 90% cpu and RAM in OVH.. pfffff

**Comment by ppumkin** [comment]
We streaming direct  to OBS now. OBS is set as listener and that seems to work fine. 
Not really worked out why srtrelay was not happy. we do 60fps.. but i doubt that could be the cause? i dont know
