### ISSUE TITLE
Adapt StreamID scheme to SRT standards

### ISSUE THREAD

**Issue by iSchluff** [voc/srtrelay#3]
https://github.com/Haivision/srt/blob/master/docs/AccessControl.md

**Comment by ravenium** [comment]
I was playing with a media server that follows this spec [https://github.com/ossrs/srs](url) , and honestly it felt quite cumbersome for streaming compared to RTMP's simple app/streamid pair.  Also, bash really doesn't like shebangs when using ffmpeg on the command line, but that might be an outlier.

That said, it's not the end of the world and would be more spec compliant than SLS.  Plus, This might be the best way to implement SRT crypto/passphrase checking for streams? 

Just a .02.

**Comment by iSchluff** [comment]
At the moment it's not really relevant anyway because all implementers of streamid I know of so far (ffmpeg and obs) just give you a text field. It would be interesting to see whether broadcast devices will allow setting a streamid. Afaik at the moment they mostly don't.

If more applications follow the official scheme it would be nice to adopt it aswell.

I think for crypto/passphrase we are dependant on https://github.com/Haivision/srtgo/issues/12 but I haven't tried it at all yet.

**Comment by fu5ha** [comment]
Small update here, most broadcast devices (my reference point here being various cheap standalone video encoder boxes on the market) allow setting the streamid field as just a text box as specified above and ultimately work quite well with the current scheme.

**Comment by ppumkin** [comment]
This is non issue.. i actually prefer this because like LiveU Solo doenst support stream ID -- so if i had multiple streams incoming... I would need multiple docker images.

This actually solves the problem nicely and is very explicit,  publish, play - it just work

Also thank you very much for this.. the multiple subscription is what I was looking for- super light weight freaking awesome!

**Comment by iSchluff** [comment]
will close this as manufacturers will probably never support it anyway

**Comment by ppumkin** [comment]
LiveU - just put in the `publish/streamname` in the stream id.. works fine.
If there is no input for that then just add it your self on the end of the url `streamid=publish/streamname`
